<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateConfigApplicationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('config_applications', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('unit_id')->nullable();
            $table->integer('is_configured')->nullable();         
            $table->unsignedBigInteger('doctor_id')->nullable();
            $table->unsignedBigInteger('department_id')->nullable();
            $table->unsignedSmallInteger('patient_category_id')->nullable();
            $table->string('country',30)->nullable();
            $table->string('state',30)->nullable();
            $table->string('district',30)->nullable();
            $table->string('pincode',30)->nullable();
            $table->string('city',30)->nullable();
            $table->string('area',30)->nullable();
            $table->unsignedBigInteger('visit_type_id')->nullable();
            $table->unsignedBigInteger('patient_source_id')->nullable();
            $table->decimal('appointment_slot',4,2)->nullable();
            $table->integer('is_ho')->nullable();
            $table->string('database_name',30)->nullable();
            $table->string('email')->nullable();
            $table->unsignedBigInteger('nurse_role_id')->nullable();
            $table->unsignedBigInteger('admin_role_id')->nullable();
            $table->unsignedBigInteger('doctor_role_id')->nullable();
            $table->integer('conftn_msg_for_add')->nullable();
            $table->integer('search_patients_interval')->nullable();
            $table->unsignedBigInteger('payment_mode_id')->nullable();
            $table->unsignedBigInteger('patho_specialization_id')->nullable();
            $table->unsignedBigInteger('pharmacy_specialization_id')->nullable();
            $table->unsignedBigInteger('embryologist_id')->nullable();
            $table->unsignedBigInteger('anesthetist_id')->nullable();
            $table->unsignedBigInteger('radiologist_id')->nullable();
            $table->unsignedBigInteger('gynecologist_id')->nullable();
            $table->unsignedBigInteger('physician_id')->nullable();
            $table->unsignedBigInteger('andriologist_id')->nullable();
            $table->unsignedBigInteger('biologist_id')->nullable();
            $table->unsignedBigInteger('consultation_id')->nullable();
            $table->unsignedBigInteger('self_company_id')->nullable();
            $table->unsignedBigInteger('self_tariff_id')->nullable();
            $table->integer('free_followup_days')->nullable();
            $table->unsignedBigInteger('free_followup_visit_type_id')->nullable();
            $table->unsignedBigInteger('pharmacy_visit_type_id')->nullable();
            $table->unsignedBigInteger('radiology_specialization_id')->nullable();
            $table->unsignedBigInteger('company_patient_source_id')->nullable();
            $table->string('local_language_file_name',30)->nullable();
            $table->string('local_language_file_path',30)->nullable();
            $table->unsignedBigInteger('self_relation_id')->nullable();
            $table->tinyInteger('apply_concession_to_staff')->comment('1:Yes,0:No')->default(0);
            $table->tinyInteger('allow_clinical_transaction')->comment('1:Yes,0:No')->default(0);
            $table->unsignedBigInteger('radiology_store_id')->nullable();
            $table->unsignedBigInteger('pathology_store_id')->nullable();
            $table->unsignedBigInteger('ot_store_id')->nullable();
            $table->tinyInteger('auto_deduct_stock_from_radiology')->nullable();
            $table->tinyInteger('auto_deduct_stock_from_pathology')->nullable();
            $table->tinyInteger('auto_generate_sample_no')->nullable();
            $table->string('date_format_id',50)->nullable();
            $table->integer('synchronized')->nullable();
            $table->string('attachment',36)->nullable();
            $table->string('attachment_file_name',36)->nullable();
            $table->integer('add_logo_to_all_reports')->nullable();
            $table->unsignedSmallInteger('pharmacy_patient_category_id')->nullable();
            $table->tinyInteger('enable_ssl')->comment('1:check,0:Uncheck')->default(0);
            $table->string('host')->nullable();
            $table->string('password')->nullable();
            $table->string('port')->nullable();
            $table->string('user_name')->nullable();
            $table->string('sms_url')->nullable();
            $table->string('sms_user_name')->nullable();
            $table->string('sms_password')->nullable();
            $table->string('print_format_id')->nullable();
            $table->unsignedBigInteger('pharmacy_store_id')->nullable();
            $table->unsignedSmallInteger('radiology_counter_id')->nullable();
            $table->unsignedSmallInteger('pharmacy_counter_id')->nullable();
            $table->tinyInteger('is_allow_discharge_request')->comment('1:Yes,0:No')->default(0);
            $table->unsignedBigInteger('pathology_department_id')->nullable();
            $table->unsignedBigInteger('radiology_department_id')->nullable();
            $table->unsignedBigInteger('oocyte_donation_id')->nullable();
            $table->unsignedBigInteger('embryo_receipent_id')->nullable();
            $table->unsignedBigInteger('oocyte_receipent_id')->nullable();
            $table->unsignedBigInteger('inhouse_lab_id')->nullable();
            $table->double('refund_amount')->nullable();
            $table->unsignedBigInteger('refund_mode')->nullable();
            $table->string('store_id_for_mark_up_service_item',20)->nullable();
            $table->unsignedBigInteger('company_category')->nullable();
            $table->integer('is_ipd')->nullable();
            $table->double('ipd_credit_limit')->nullable();
            $table->double('opd_credit_limit')->nullable();
            $table->integer('item_expired_indays')->nullable();
            $table->string('default_country_code',10)->nullable();
            $table->integer('is_opd')->nullable();
            $table->integer('is_counter_login')->nullable();
            $table->unsignedBigInteger('opd_counter_id')->nullable();
            $table->unsignedBigInteger('ipd_counter_id')->nullable();
            $table->unsignedBigInteger('lab_counter_id')->nullable();
            $table->unsignedBigInteger('doctor_type_for_referral')->nullable();
            $table->unsignedBigInteger('identity_for_international_patient')->nullable();
            $table->unsignedBigInteger('authorization_level_for_refund_id')->nullable();
            $table->unsignedBigInteger('authorization_level_for_concession_id')->nullable();
            $table->integer('address_type_id')->nullable();
            $table->unsignedBigInteger('country_id')->nullable();
            $table->unsignedBigInteger('state_id')->nullable();
            $table->unsignedBigInteger('city_id')->nullable();
            $table->integer('region_id')->nullable();
            $table->integer('category_id')->nullable();
            $table->string('marital_status',20)->nullable();
            $table->string('web_site',40)->nullable();
            $table->integer('is_sell_by_selling_unit')->nullable();
            $table->unsignedBigInteger('is_central_purchase_store')->nullable();
            $table->integer('indent_store_id')->nullable();
            $table->integer('password_to_modify_radiology_report')->nullable();
            $table->unsignedBigInteger('pathology_visit_type_id')->nullable();
            $table->unsignedBigInteger('pathology_company_type_id')->nullable();
            $table->integer('pathologist_id')->nullable();
            $table->integer('is_photo_move_to_server')->nullable();
            $table->string('disclaimer')->nullable();
            $table->integer('is_pharmacy_ipd')->nullable();
            $table->double('ipd_pharmacy_credit_limit')->nullable();
            $table->integer('is_pharmacy_opd')->nullable();
            $table->double('opd_pharmacy_credit_limit')->nullable();
            $table->integer('close_visit_minute')->nullable();
            $table->double('patient_cash_limit')->nullable();
            $table->double('billing_exceed_limit')->nullable();
            $table->unsignedSmallInteger('patient_reg_type')->nullable();
            $table->foreign('unit_id')->references('id')->on('units')->onDelete('cascade');
            $table->foreign('doctor_id')->references('id')->on('doctors')->onDelete('cascade'); 
            $table->foreign('department_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('patient_category_id')->references('id')->on('patient_categories')->onDelete('cascade');
            $table->foreign('visit_type_id')->references('id')->on('visit_types')->onDelete('cascade');
            $table->foreign('patient_source_id')->references('id')->on('patient_sources')->onDelete('cascade');
            $table->foreign('nurse_role_id')->references('id')->on('role_masters')->onDelete('cascade');
            $table->foreign('admin_role_id')->references('id')->on('role_masters')->onDelete('cascade');
            $table->foreign('doctor_role_id')->references('id')->on('role_masters')->onDelete('cascade');
            $table->foreign('payment_mode_id')->references('id')->on('mode_of_payments')->onDelete('cascade');
            $table->foreign('patho_specialization_id')->references('id')->on('specializations')->onDelete('cascade');
            $table->foreign('pharmacy_specialization_id')->references('id')->on('specializations')->onDelete('cascade');
            $table->foreign('embryologist_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('anesthetist_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('radiologist_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('gynecologist_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('physician_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('andriologist_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('biologist_id')->references('id')->on('classifications')->onDelete('cascade');
            $table->foreign('consultation_id')->references('id')->on('visit_types')->onDelete('cascade');
            $table->foreign('self_company_id')->references('id')->on('company_masters')->onDelete('cascade');
            $table->foreign('self_tariff_id')->references('id')->on('tariff_masters')->onDelete('cascade');
            $table->foreign('free_followup_visit_type_id')->references('id')->on('visit_types')->onDelete('cascade');
            $table->foreign('pharmacy_visit_type_id')->references('id')->on('visit_types')->onDelete('cascade');
            $table->foreign('radiology_specialization_id')->references('id')->on('specializations')->onDelete('cascade');
            $table->foreign('company_patient_source_id')->references('id')->on('patient_sources')->onDelete('cascade');
            $table->foreign('self_relation_id')->references('id')->on('patient_sources')->onDelete('cascade');
            $table->foreign('radiology_store_id')->references('id')->on('stores')->onDelete('cascade');
            $table->foreign('pathology_store_id')->references('id')->on('stores')->onDelete('cascade');
            $table->foreign('ot_store_id')->references('id')->on('stores')->onDelete('cascade');
            $table->foreign('pharmacy_patient_category_id')->references('id')->on('patient_categories')->onDelete('cascade');
            $table->foreign('pharmacy_store_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('radiology_counter_id')->references('id')->on('patient_categories')->onDelete('cascade');
            $table->foreign('pharmacy_counter_id')->references('id')->on('patient_categories')->onDelete('cascade');
            $table->foreign('pathology_department_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('radiology_department_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('oocyte_donation_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('embryo_receipent_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('oocyte_receipent_id')->references('id')->on('departments')->onDelete('cascade');
            $table->foreign('refund_mode')->references('id')->on('mode_of_payments')->onDelete('cascade');
            $table->foreign('company_category')->references('id')->on('company_masters')->onDelete('cascade');
            $table->foreign('opd_counter_id')->references('id')->on('cash_counters')->onDelete('cascade');
            $table->foreign('ipd_counter_id')->references('id')->on('cash_counters')->onDelete('cascade');
            $table->foreign('lab_counter_id')->references('id')->on('cash_counters')->onDelete('cascade');
            $table->foreign('doctor_type_for_referral')->references('id')->on('doctor_categories')->onDelete('cascade');
            $table->foreign('identity_for_international_patient')->references('id')->on('identity_masters')->onDelete('cascade');
            // $table->foreign('authorization_level_for_refund_id')->references('id')->on('refunds')->onDelete('cascade');
            // $table->foreign('authorization_level_for_concession_id')->references('id')->on('refunds')->onDelete('cascade');
            $table->foreign('country_id')->references('id')->on('countries')->onDelete('cascade');
            $table->foreign('state_id')->references('id')->on('states')->onDelete('cascade');
            $table->foreign('city_id')->references('id')->on('cities')->onDelete('cascade');
            $table->foreign('is_central_purchase_store')->references('id')->on('stores')->onDelete('cascade');
            $table->foreign('pathology_visit_type_id')->references('id')->on('visit_types')->onDelete('cascade');
            $table->foreign('pathology_company_type_id')->references('id')->on('company_type_masters')->onDelete('cascade');
            $table->foreign('patient_reg_type')->references('id')->on('patient_categories')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('config_applications');
    }
}
